name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps

    - name: Build the Next.js app
      run: npm run build

    - name: Deploy or Push Docker Image (Optional)
      run: |
        docker build -t docker.io/akashgupta2233/ai-assisted-blog:latest .
        docker push docker.io/akashgupta2233/ai-assisted-blog:latest
